apiVersion: apps/v1
kind: Deployment
metadata:
  name: heavy-app
  namespace: default
spec:
  selector:
    matchLabels:
      app: heavy-app
  template:
    metadata:
      labels:
        app: heavy-app
    spec:
      containers:
      - name: heavy-app
        image: registry.k8s.io/hpa-example
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: heavy-app
  labels:
    app: heavy-app
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: heavy-app
