# syntax=docker/dockerfile:1
FROM --platform=linux/amd64 ubuntu:22.04

RUN apt-get update && \
    apt-get install -y iptables

COPY init.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/init.sh

ENTRYPOINT ["init.sh"]
