---
apiVersion: v1
kind: Namespace
metadata:
  name: back
---
apiVersion: v1
kind: Namespace
metadata:
  name: api
---
apiVersion: v1
kind: Namespace
metadata:
  name: worker
---
apiVersion: v1
kind: Namespace
metadata:
  name: payment
