version: "3"
services:
  consul:
    image: consul:1.14.4
    command: ["consul","agent","-config-file=/config/consul.hcl","-config-dir=/config"]
    volumes:
      - "./consul_config:/config"
    ports:
      - 8500:8500
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2

  web:
    image: nicholasjackson/fake-service:v0.19.1
    environment:
      LISTEN_ADDR: 0.0.0.0:9091
      UPSTREAM_URIS: "http://localhost:9092"
      MESSAGE: "Hello World"
      NAME: "web"
      SERVER_TYPE: "http"
    ports:
    - "9091:9091"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
  web_proxy:
    image: nicholasjackson/consul-envoy:1.14.4-v1.25.1
    restart: always
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/web.hcl
      CENTRAL_CONFIG_DIR: /central_config
    volumes:
      - "./service_config:/config"
      - "./central_config:/central_config"
    command: ["consul", "connect", "envoy","-sidecar-for", "web"]
    network_mode: "service:web"

  api_v1:
    image: nicholasjackson/fake-service:v0.19.1
    hostname: api
    environment:
      LISTEN_ADDR: 0.0.0.0:9092
      MESSAGE: "Hello World"
      NAME: "api-v1"
      SERVER_TYPE: "http"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
  api_v1_proxy:
    image: nicholasjackson/consul-envoy:1.14.4-v1.25.1
    restart: always
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/api_v1.hcl
      CENTRAL_CONFIG_DIR: /central_config
    volumes:
      - "./service_config:/config"
      - "./central_config:/central_config"
    command: ["consul", "connect", "envoy","-sidecar-for", "api-v1"]
    network_mode: "service:api_v1"

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - "./prometheus_config/prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6

networks:
  vpcbr:
    driver: bridge
    name: seccamp-consul-circuit-breaker
    ipam:
      config:
        - subnet: 10.5.0.0/16
