apiVersion: v1
kind: Pod
metadata:
  name: bpftrace- # ここに a-1 や b-1 などの prefix を入力. e.g. bpftrace-a-1
  namespace: default
spec:
  hostNetwork: true
  hostPID: true
  containers:
    - name: bpftrace
      image: mrtc0/bpftrace
      command: ['sleep', 'inf']
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /usr/src
          name: usr
          readOnly: true
        - mountPath: /sys/kernel/debug
          name: debug
  volumes:
    - hostPath:
        path: /lib/modules
      name: modules
    - hostPath:
        path: /usr/src
      name: usr
    - hostPath:
        path: /sys/kernel/debug
      name: debug

